## number of exporter instances
##
replicaCount: 1

## restart policy for all containers
##
restartPolicy: Always

env:
  AWS_REGION: eu-west-1
  INTERVAL: 60

image:
  repository: hapu2000/sqs-exporter
  tag: latest
  pullPolicy: IfNotPresent

resources: {}
  # limits:
  #   memory: 128Mi
  # requests:
  #   cpu: 20m
  #   memory: 32Mi

priorityClassName: ""

nodeSelector: {}

tolerations: {}

affinity: {}

podAnnotations: {}

service:
  type: ClusterIP
  httpPort: 9108
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9108"